### ISSUE TITLE
2. Monitor not supported?

### ISSUE THREAD

**Issue by revunix** [n3PH1lim/Mojave-Dynamic-Wallpaper#1]
Hey,

thanks for this script, works good but i isn't support a 2. or 3. monitor. Is it possible to add multi-monitor support?

greetings,
alex

**Comment by n3PH1lim** [comment]
Changed something I have at the Moment only 1 Monitor but it should work.

**Comment by n3PH1lim** [comment]
#304570feb9d68d948b88031a09a8f2724a8a7577
